DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(500) NOT NULL,
  content VARCHAR(8000),
  createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  img VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id)
);