DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE friends (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  friends_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);