DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  dob DATE NOT NULL,
  userName VARCHAR(255) NOT NULL,
  createdAt DATE NOT NULL DEFAULT(GETDATE())
);